# workstation-setup: managed sway window borders
# Minimal window borders
default_border pixel 2
default_floating_border pixel 2

#                        border    background text      indicator child_border
client.focused           #e88923   #1e1e1e    #ffffff   #e88923   #e88923
client.focused_inactive  #242424   #1e1e1e    #888888   #242424   #242424
client.unfocused         #242424   #1e1e1e    #777777   #242424   #242424
client.urgent            #e06c75   #1e1e1e    #ffffff   #e06c75   #e06c75
