#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

grep -Fq -- '--sway' "$ROOT_DIR/install.sh"
grep -Fq -- '--gnome' "$ROOT_DIR/install.sh"
grep -Fq 'DESKTOP_ENV=sway' "$ROOT_DIR/install.sh"
grep -Fq 'DESKTOP_ENV=gnome' "$ROOT_DIR/install.sh"
grep -Fq 'start_sudo_keepalive' "$ROOT_DIR/install.sh"
grep -Fq 'sudo -n true' "$ROOT_DIR/lib/common.sh"
grep -Fq 'bash "$module" </dev/null' "$ROOT_DIR/install.sh"
grep -Fq 'dnf install -y --skip-unavailable' "$ROOT_DIR/lib/common.sh"
grep -Fq 'sdkman_auto_answer=true' "$ROOT_DIR/modules/30-sdkman.sh"
grep -Fq 'workstation-setup.jpg' "$ROOT_DIR/templates/sway/config"
grep -Fq 'wpctl set-volume' "$ROOT_DIR/templates/sway/config"
grep -Fq 'set $term kitty' "$ROOT_DIR/templates/sway/config"
grep -Fq 'set $lock $HOME/.local/bin/workstation-lock' "$ROOT_DIR/templates/sway/config"
grep -Fq 'set $menu fuzzel' "$ROOT_DIR/templates/sway/config"
grep -Fq 'bindsym $mod+b splith' "$ROOT_DIR/templates/sway/config"
grep -Fq 'bindsym $mod+v splitv' "$ROOT_DIR/templates/sway/config"
grep -Fq 'bindsym $mod+f fullscreen toggle' "$ROOT_DIR/templates/sway/config"
grep -Fq 'app_id="^lxqt-policykit-agent$"' "$ROOT_DIR/templates/sway/policykit-window.conf"
grep -Fq 'resize set width 560 height 300' "$ROOT_DIR/templates/sway/policykit-window.conf"
grep -Fq 'app_id="^nm-connection-editor$"' "$ROOT_DIR/templates/sway/desktop-app-windows.conf"
grep -Fq 'app_id="^org.pulseaudio.pavucontrol$"' "$ROOT_DIR/templates/sway/desktop-app-windows.conf"
grep -Fq 'Super + B                 Dividi in orizzontale' "$ROOT_DIR/bin/sway-shortcuts"
grep -Fq 'Super + V                 Dividi in verticale' "$ROOT_DIR/bin/sway-shortcuts"
grep -Fq 'Super + F                 Attiva/disattiva tutto schermo' "$ROOT_DIR/bin/sway-shortcuts"
grep -Fq 'fields=filename,name,generic,keywords,comment' "$ROOT_DIR/templates/sway/fuzzel.ini"
grep -Fq 'placeholder=Cerca applicazioni…' "$ROOT_DIR/templates/sway/fuzzel.ini"
grep -Fq 'selection-radius=8' "$ROOT_DIR/templates/sway/fuzzel.ini"
grep -Fq 'radius=14' "$ROOT_DIR/templates/sway/fuzzel.ini"
grep -Fq 'templates/sway/fuzzel.ini' "$ROOT_DIR/modules/75-sway-desktop.sh"
grep -Fq 'active_theme="$("$HOME/.local/bin/workstation-theme" current)"' "$ROOT_DIR/modules/75-sway-desktop.sh"
grep -Fq 'bash "$ROOT_DIR/modules/26-kitty.sh" </dev/null' "$ROOT_DIR/modules/75-sway-desktop.sh"
grep -Fq 'install_available_packages kitty kitty-terminfo ncurses zsh' "$ROOT_DIR/modules/26-kitty.sh"
grep -Fq 'lxqt-policykit' "$ROOT_DIR/modules/75-sway-desktop.sh"
grep -Fq 'cascadia-mono-nf-fonts' "$ROOT_DIR/modules/75-sway-desktop.sh"
grep -Fq '$HOME/.local/bin/workstation-policykit-agent' "$ROOT_DIR/templates/sway/config"
! grep -Fq 'polkit-gnome' "$ROOT_DIR/modules/75-sway-desktop.sh"
! grep -Fq 'polkit-gnome' "$ROOT_DIR/templates/sway/config"
grep -Fq "timeout 3600 '\$lock'" "$ROOT_DIR/templates/sway/config"
grep -Fq 'xkb_layout it' "$ROOT_DIR/templates/sway/config"
grep -Fq 'gaps inner 8' "$ROOT_DIR/templates/sway/config"
grep -Fq 'gaps outer 0' "$ROOT_DIR/templates/sway/config"
grep -Fq '"height": 30' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq '"format": "󰍛 {usage}%"' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq '"format": "{icon} {capacity}%"' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq '"custom/cliamp"' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq 'on-click-right": "$HOME/.local/bin/cliamp-widget close"' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq 'on-click": "$HOME/.local/bin/workstation-power-profile-menu"' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq "'Dev 60%' 'Risparmio' 'Prestazioni'" "$ROOT_DIR/bin/workstation-power-profile-menu"
grep -Fq -- '--no-exit-on-keyboard-focus-loss' "$ROOT_DIR/bin/workstation-power-profile-menu"
grep -Fq '"format": "󰘚 {percentage}%"' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq '"tooltip-format": "<tt>{calendar}</tt>"' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq '"iso8601": true' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq '"on-scroll-up": "shift_up"' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq 'group/tray-expander' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq '"on-click": "$HOME/.local/bin/workstation-network-editor"' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq '"tray": {"icon-size": 15, "spacing": 14, "cursor": true}' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq '"battery", "custom/power"' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq '"on-click": "$HOME/.local/bin/workstation-power-menu"' "$ROOT_DIR/templates/sway/waybar-config.jsonc"
grep -Fq 'CaskaydiaMono Nerd Font' "$ROOT_DIR/templates/sway/waybar-style.css"
grep -Fq '#network:hover,' "$ROOT_DIR/templates/sway/waybar-style.css"
grep -Fq 'HandleLidSwitch=suspend' "$ROOT_DIR/templates/logind-lid.conf"
grep -Fq 'HandleLidSwitchExternalPower=suspend' "$ROOT_DIR/templates/logind-lid.conf"
grep -Fq 'HandleLidSwitchDocked=suspend' "$ROOT_DIR/templates/logind-lid.conf"
grep -Fq '/etc/systemd/logind.conf.d/90-workstation-setup-lid.conf' "$ROOT_DIR/modules/75-sway-desktop.sh"
grep -Fq 'xdg-desktop-portal/sway-portals.conf' "$ROOT_DIR/modules/75-sway-desktop.sh"
grep -Fq 'gnome-shell-extension-dash-to-dock' "$ROOT_DIR/modules/76-gnome-desktop.sh"
test -x "$ROOT_DIR/bin/waybar-cpu-temperature"
test -x "$ROOT_DIR/bin/sway-shortcuts"
test -x "$ROOT_DIR/bin/workstation-theme"
test -x "$ROOT_DIR/bin/workstation-lock"
test -x "$ROOT_DIR/bin/workstation-network-editor"
test -x "$ROOT_DIR/bin/workstation-policykit-agent"
test -x "$ROOT_DIR/bin/workstation-power-menu"
grep -Fq 'GTK_THEME="$gtk_theme" nm-connection-editor' "$ROOT_DIR/bin/workstation-network-editor"
grep -Fq 'bin/workstation-network-editor' "$ROOT_DIR/modules/75-sway-desktop.sh"
grep -Fq 'QT_QPA_PLATFORMTHEME=gtk3' "$ROOT_DIR/bin/workstation-policykit-agent"
grep -Fq 'bin/workstation-policykit-agent' "$ROOT_DIR/modules/75-sway-desktop.sh"
grep -Fq 'bin/workstation-power-menu' "$ROOT_DIR/modules/75-sway-desktop.sh"
grep -Fq "pgrep -f '^/usr/libexec/lxqt-policykit-agent\$'" "$ROOT_DIR/bin/workstation-theme"
grep -Fq '@import url("theme.css");' "$ROOT_DIR/templates/sway/waybar-style.css"
grep -Fq 'include theme.conf' "$ROOT_DIR/templates/kitty.conf"
grep -Fq 'Name=Cambia tema chiaro o scuro' "$ROOT_DIR/templates/sway/workstation-theme.desktop"
grep -Fq 'default-timeout=10000' "$ROOT_DIR/templates/themes/dark/mako.conf"
grep -Fq 'default-timeout=10000' "$ROOT_DIR/templates/themes/light/mako.conf"
grep -Fq 'Name=Tasti rapidi e scorciatoie da tastiera' "$ROOT_DIR/templates/sway/sway-shortcuts.desktop"
grep -Fq 'GenericName=Tasti e shortcut di Sway' "$ROOT_DIR/templates/sway/sway-shortcuts.desktop"
grep -Fq 'Keywords=scorciatoie;shortcut;tasti;comandi;tastiera;sway;' "$ROOT_DIR/templates/sway/sway-shortcuts.desktop"
grep -Fq 'Exec=/usr/bin/zsh -lc "exec \\$HOME/.local/bin/sway-shortcuts"' "$ROOT_DIR/templates/sway/sway-shortcuts.desktop"

printf '%s\n' 'OK   configurazione Sway e sudo non interattivo'
